- name: installaiton of ngnix
  hosts: local
  connection: local #Only for local host only we have to mention connection also
  tasks:
  - name: installing ngnix
    ansible.builtin.package:
      name: ngnix
      state: present
  
  - name: starting nginx
    ansible.builtin.service:
      name: nginx
      state: started  #similar to systemctl start nginx
      enabled: yes  #similar to systemctl enable nginx