- name: Task level variable
  hosts: local
  connection: local
  tasks:
  - name: Using task level variable
    vars:
      city: Vizianagaram
      State: Andhra Pradesh
      country: INDIA
    ansible.builtin.debug:
      msg: "Hello Team, I am from {{city}} district in the state of {{State}} and i love my {{country}}."
