- name: Using variables from file
  hosts: local
  connection: local
  vars_files:
  - variable.yaml
  taks:
  - name: getting variables from file
    ansible.builtin.debug:
      msg: hello i am surya with id {{id}} from dept {{branch}} in {{college}} college.