- name: variables form prompt
  hosts: local
  connection: local
  vars_prompt:
  - name: USERNAME
    prompt: Please enter username
    private: false

  - name: PASSWORD
    prompt: Please enter password
    private: true
  
  tasks:
  - name: getting variables from prompt
    ansible.builtin.debug:
      msg : "Hello username is {{USERNAME}} and password is {{PASSWORD}}" 

