- name: Variables from inventory group
  hosts: local
  connection: local
  tasks:  
  - name: vars from inventory
    ansible.builtin.debug:
      msg: "Hello I am learning {{ COURSE }}, Duration: {{ DURATION }}, Trainer is: {{ TRAINER }}"