- name: Datatypes
  hosts: local
  connection: local
  vars:
    COURSE: aws devsecops
    DURATION: 11hrs
    TRAINER: surya Prakash
    IS_ALIVE: true
    Tools:
    - linux
    - shell
    - ansible
    concepts:
      CI : jekins
      scripting: "shell, ansible, terrafom"
  tasks:
  - name: Datatypes: lists and objects
    ansible.builtin.debug:
      msg: "Course is: {{ COURSE }}, Duration: {{ DURATION }}, is live?: {{ IS_LIVE }}, Tools are: {{ TOOLS }}, Concepts are: {{ CONCETPS }}"

