- name: conditons
  hosts: local
  connection: local
  vars: 
    Number: 10
  tasks:
  - name: display the number based on condition
    ansible.builtin.debug:
      msg: "The given number {{Number}} is lessthan 100"
    when: Number < 100