- name: playbook controlling usinf ansible_facts
  hosts:  frontend
  become: yes #to get sudo acces (or) while running in linux we can give -b to become root user
  tasks:
  - name: install nginx if os_family is redhat
    ansible.builtin.dnf:
      name: nginx
      state: present
    when: ansible_os_family == "RedHat"

  - name: install nginx id os_family is debian
    ansible.builtin.apt:
      name: nginx
      state:  present
    when: ansible_os_family == "Debian"