- name: loops
  hosts:  local
  connection: local
  become: yes
  tasks:
  - name: printing name using loops
    ansible.builtin.debug:
      msg: printing {{  item }} #item here is reserved keyword to display data using loops
    loop:
    - srinivas
    - laxmi
    - surya
    - Prakash
    - ravi
