- name: configuration with dynamic inventory
  hosts: dynamic_frontend #name taken from inventory.aws_ec2.yaml
  serial: 5 # if we mention serial as five, it will done the task in 5 servers then next 5 servers
  become: yes
  tasks:
  - name: installing nginx
    ansible.builtin.dnf:
      name: nginx
      state: installed
    
  - name: running nginx
    ansible.builtin.service:
      name: nginx
      state: started
      enabled: yes


# TO install nginx to dynamic IPS, ansible should run parallely